# Generated by Django 2.2.17 on 2020-12-17 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WifeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.SmallIntegerField()),
                ('gender', models.BooleanField(default=0)),
                ('point', models.IntegerField()),
                ('hProduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anim.ProductionInfo')),
            ],
        ),
    ]
